language: java
jdk:
- oraclejdk8
node_js:
- '7'
services:
- mysql
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- pip install --user codecov
- nvm install 7
- npm install -g yarn
- yarn install
- "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
install:
- cd mr-gui && yarn install && cd ..
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
- mysql -e "create database IF NOT EXISTS metadata_registry; grant all on metadata_registry.* to 'root';SET
  GLOBAL TRANSACTION ISOLATION LEVEL SERIALIZABLE;" -uroot
- mysql -e "create database IF NOT EXISTS sr; grant all on sr.* to 'root';" -uroot
script:
- mvn test
- cd mr-gui && yarn install
after_success:
- codecov