language: java
jdk:
- oraclejdk8
node_js:
- '7'
services:
- mysql
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- pip install --user codecov
- nvm install 7
- npm install -g yarn
- yarn install
install:
- cd manage-gui && yarn install && cd ..
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
- mysql -e "create database IF NOT EXISTS manage; grant all on manage.* to 'root';SET
  GLOBAL TRANSACTION ISOLATION LEVEL SERIALIZABLE;" -uroot
- mysql -e "create database IF NOT EXISTS sr; grant all on sr.* to 'root';" -uroot
- mysql -e "create database IF NOT EXISTS eb; grant all on eb.* to 'root';" -uroot
script:
- mvn test
- cd manage && yarn install
after_success:
- codecov