logging:
  level:
    org.springframework.data.mongodb: DEBUG

server:
  contextPath: /mr/api
  server-header:
  session:
    timeout: 28800

metadata_configuration_path: classpath:/metadata_configuration
migrate_data_from_janus: false

security:
  internal_user_name: openconext
  internal_password: secret

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/metadata
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost/metadata_registry?autoReconnect=true&useSSL=false
    username: root
    password:
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1

  main:
    banner-mode: "off"

# We disable all endpoints except health for the load-balancer and info for git information.
endpoints:
  enabled: false
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
